#requires -Version 5.1
<#
.SYNOPSIS
  Regenerates docs-site/docs/reference/fmf-hooks-catalog.md from FrikaMF HookNames.cs and EventIds.cs
#>
param(
    [switch]$SkipChangelogNote
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$scriptRoot = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $PSCommandPath }
$repoRoot = Resolve-Path (Join-Path $scriptRoot '..')
$hookNamesPath = Join-Path $repoRoot 'FrikaMF/HookNames.cs'
$eventIdsPath = Join-Path $repoRoot 'FrikaMF/EventIds.cs'
$outPath = Join-Path $repoRoot 'docs-site/docs/reference/fmf-hooks-catalog.md'

if (-not (Test-Path -LiteralPath $hookNamesPath)) {
    throw "Not found: $hookNamesPath"
}
if (-not (Test-Path -LiteralPath $eventIdsPath)) {
    throw "Not found: $eventIdsPath"
}

$hookSource = Get-Content -LiteralPath $hookNamesPath -Raw
$eventSource = Get-Content -LiteralPath $eventIdsPath -Raw

# const string Name = "FFM....";
$constRegex = 'public const string (?<field>\w+)\s*=\s*"(?<hook>FFM\.[^"]+)";'
$hookRows = [System.Collections.Generic.List[object]]::new()
foreach ($m in [regex]::Matches($hookSource, $constRegex)) {
    $hookRows.Add([ordered]@{
            Field = $m.Groups['field'].Value
            Hook  = $m.Groups['hook'].Value
        })
}

# [EventIds.Something] = ConstName,
$mapRegex = '\[\s*EventIds\.(?<ev>\w+)\s*\]\s*=\s*(?<field>\w+)\s*,'
$idToField = @{}
foreach ($m in [regex]::Matches($hookSource, $mapRegex)) {
    $idToField[$m.Groups['ev'].Value] = $m.Groups['field'].Value
}

# FrikaMF.EventIds.xxx in mapping
$mapRegex2 = '\[\s*FrikaMF\.EventIds\.(?<ev>\w+)\s*\]\s*=\s*(?<field>\w+)\s*,'
foreach ($m in [regex]::Matches($hookSource, $mapRegex2)) {
    $idToField[$m.Groups['ev'].Value] = $m.Groups['field'].Value
}

# public const uint Name = number;
$evRegex = 'public const uint (?<name>\w+)\s*=\s*(?<num>\d+)\s*;'
$eventNums = @{}
foreach ($m in [regex]::Matches($eventSource, $evRegex)) {
    $eventNums[$m.Groups['name'].Value] = [uint32]$m.Groups['num'].Value
}

$generatedUtc = (Get-Date).ToUniversalTime().ToString('yyyy-MM-dd HH:mm:ss UTC')
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('---')
[void]$sb.AppendLine('id: fmf-hooks-catalog')
[void]$sb.AppendLine('title: FMF hooks catalog')
[void]$sb.AppendLine('slug: /reference/fmf-hooks-catalog')
[void]$sb.AppendLine('description: Auto-generated catalog of hook strings and event id mappings from FrikaMF sources.')
[void]$sb.AppendLine('---')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('<!-- AUTO-GENERATED by tools/Generate-FmfHookCatalog.ps1 - DO NOT EDIT BY HAND -->')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('# FMF hooks catalog')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('This page is **generated** from `FrikaMF/HookNames.cs` and `FrikaMF/EventIds.cs`.')
if (-not $SkipChangelogNote) {
    [void]$sb.AppendLine('Regenerate after hook changes: `./tools/Generate-FmfHookCatalog.ps1`')
}
[void]$sb.AppendLine('')
[void]$sb.AppendLine("**Generated:** $generatedUtc")
[void]$sb.AppendLine('')
[void]$sb.AppendLine('## Hook string constants')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('| C# field | Hook string |')
[void]$sb.AppendLine('|----------|-------------|')

$seen = @{}
foreach ($row in ($hookRows | Sort-Object { $_.Hook })) {
    if ($seen.ContainsKey($row.Hook)) { continue }
    $seen[$row.Hook] = $true
    [void]$sb.AppendLine('| ``' + $row.Field + '`` | ``' + $row.Hook + '`` |')
}

[void]$sb.AppendLine('')
[void]$sb.AppendLine('## Event id to hook mapping')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('| Event id (uint) | EventIds name | Resolves to field | Hook string |')
[void]$sb.AppendLine('|-----------------|---------------|---------------------|-------------|')

foreach ($evName in ($idToField.Keys | Sort-Object)) {
    $field = $idToField[$evName]
    if (-not $eventNums.ContainsKey($evName)) { continue }
    $num = $eventNums[$evName]
    $hookStr = ($hookRows | Where-Object { $_.Field -eq $field } | Select-Object -First 1).Hook
    if (-not $hookStr) { $hookStr = '*(see HookNames.Resolve fallback)*' }
    [void]$sb.AppendLine("| $num | ``$evName`` | ``$field`` | ``$hookStr`` |")
}

[void]$sb.AppendLine('')
[void]$sb.AppendLine('## Fallback')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('Unknown event ids resolve to ``FFM.Framework.Unknown.OnEvent`` in `HookNames.Resolve`.')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('## See also')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('- [FMF hook naming](./fmf-hook-naming.md)')
[void]$sb.AppendLine('- [EventIds source](https://github.com/mleem97/gregFramework/blob/master/FrikaMF/EventIds.cs)')
[void]$sb.AppendLine('- [HookNames source](https://github.com/mleem97/gregFramework/blob/master/FrikaMF/HookNames.cs)')

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($outPath, $sb.ToString(), $utf8NoBom)
Write-Host "Wrote $outPath"
